platform :ios, '10.0'

use_frameworks!

target 'YSKitProject' do
  
  # 自己的库
  pod 'YSKit', :path => 'YSKit'
  
  # Rx
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  
  # 常用工具库
  pod 'Alamofire', '5.6.4'
  pod 'SnapKit', '5.6.0'
  pod 'SDWebImage', '5.14.3'
  
end
