platform :ios, '10.0'

use_frameworks!

target 'YSKitProject' do
  
  # 自己的库
  pod 'YSKit', :path => 'YSKit'
  
  # Rx
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'RxAlamofire', '6.1.1'
  
  # 常用工具库
  pod 'Alamofire', '5.6.4'
  pod 'Socket.IO-Client-Swift', '16.0.1'
  pod 'SnapKit', '5.6.0'
  pod 'SDWebImage', '5.14.3'
  pod 'MJRefresh', '3.7.5'
  pod 'SwiftyJSON', '5.0.1'
  
end
